MemberCenter/Controllers/PointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Data.Entity.Validation;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using MemberCenter.Models;
using MemberCenter.Helper;
using VapLib;

namespace MemberCenter.Controllers
{
    public class PointsController : BaseController
    {

        //
        // GET: /Points/History
        public ActionResult History()
        {
            IEnumerable<ConsumptionViewModel> model = from row in CurrentUser.PointTransaction
                                                      orderby row.DateTime descending
                                                      select new ConsumptionViewModel
                                                      {
                                                          DateTime = row.DateTime,
                                                          Amount = row.Amount,
                                                          Comment = row.Comment,
                                                          Type = row.Type,
                                                      };
            SetMyAccountViewModel();
            return View(model);
        }

        //
        // GET: /Points/Transfer
        public ActionResult Transfer()
        {
            if (GetSystemSettingBoolean("SystemIsLocked"))
            {
                TempData["ActionMessage"] = "系统维护中，暂停交易！";
                return RedirectToAction("Error", "Message");
            }
            SetMyAccountViewModel();
            return View(new PointTransferViewModel
            {
                AvailableAmount = CurrentUser.Point1,
                MinRequestAmount = (int)GetSystemSettingDecimal("PointsRate"),
                MaxRequestAmount = (Int32)(Math.Floor(CurrentUser.Point1 / GetSystemSettingDecimal("PointsRate")) * GetSystemSettingDecimal("PointsRate"))
            });
        }

        //
        // POST: /Points/Transfer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Transfer(PointTransferViewModel model)
        {
            if (ModelState.IsValid)
            {
                Member mUser = null;
                bool hasError = false;
                //Validation,
                //Check current balance is much than request amount
                if (model.Amount > CurrentUser.Point1 || model.Amount < GetSystemSettingDecimal("PointsRate"))
                {
                    ModelState.AddModelError("", "转账数量有误，请重试！");
                    hasError = true;
                }

                if (!CurrentUser.Password2.Equals(model.Password))
                {
                    ModelState.AddModelError("", "交易密码错误");
                    hasError = true;
                }

                //Check target member exists
                if (model.User.IndexOf("@") > 0)
                {
                    mUser = db.Members.SingleOrDefault(m => m.Email.Equals(model.User, StringComparison.InvariantCultureIgnoreCase));
                    if (mUser == null)
                    {
                        ModelState.AddModelError("", "找不到接受会员，请重试！");
                        hasError = true;
                    }
                }
                else
                {
                    try
                    {
                        int id = int.Parse(model.User);
                        mUser = db.Members.SingleOrDefault(m => m.Id == id);
                        if (mUser == null)
                        {
                            ModelState.AddModelError("", "找不到接受会员，请重试！");
                            hasError = true;
                        }
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", "找不到接受会员，请重试！");
                        hasError = true;
                    }
                }

                if (mUser != null && CurrentUser.Id == mUser.Id)
                {
                    ModelState.AddModelError("", "接受会员不能是自己，请重试！");
                    hasError = true;
                }

                if (mUser != null && !hasError)
                {
                    //Add Transaction record to db
                    CurrentUser.PointTransaction.Add(new PointTransaction
                    {
                        DateTime = DateTime.Now,
                        Amount = -model.Amount,
                        Type = 兑换券记录类型.会员转出.ToString(),
                        Status = 兑换券状态.可用.ToString(),
                        Comment = "转出至会员(UID:" + mUser.Id + ")",
                    });

                    mUser.PointTransaction.Add(new PointTransaction
                    {
                        DateTime = DateTime.Now,
                        Amount = model.Amount,
                        Type = 兑换券记录类型.会员转入.ToString(),
                        Status = 兑换券状态.可用.ToString(),
                        Comment = "会员(UID:" + CurrentUser.Id + ")转入",
                    });

                    //Calculate and update balance
                    CurrentUser.Point1 -= model.Amount;
                    mUser.Point1 += model.Amount;

                    db.SaveChanges();
                    ViewBag.ActionMessage = "购物券转账成功！";
                    TempData["ActionMessage"] = ViewBag.ActionMessage;
                    return RedirectToAction("Success", "Message");
                }
            }
            SetMyAccountViewModel();
            return View(new PointTransferViewModel
            {
                AvailableAmount = CurrentUser.Point1,
                MinRequestAmount = (int)GetSystemSettingDecimal("PointsRate"),
                MaxRequestAmount = (Int32)(Math.Floor(CurrentUser.Point1 / GetSystemSettingDecimal("PointsRate")) * GetSystemSettingDecimal("PointsRate"))
            });
        }

        //
        // GET: /Points/Buy
        public ActionResult Buy()
        {
            if (GetSystemSettingBoolean("SystemIsLocked"))
            {
                TempData["ActionMessage"] = "系统维护中，暂停交易！";
                return RedirectToAction("Error", "Message");
            }
            if (CurrentUser.Cash1 < GetSystemSettingDecimal("PointsRate"))
            {
                ModelState.AddModelError("", "对不起，您的账户可用资金不足￥" + GetSystemSettingDecimal("PointsRate").ToString("0,0.00") + "，请先充值。");
            }

            SetMyAccountViewModel();
            return View(CalculatePointBuyModel());
        }


        // POST: /Points/Buy
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Buy(PointBuyViewModel model)
        {
            if (GetSystemSettingBoolean("SystemIsLocked"))
            {
                TempData["ActionMessage"] = "系统维护中，暂停交易！";
                return RedirectToAction("Error", "Message");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var mMinRequestAmount = (int)GetSystemSettingDecimal("PointsRate");
                    var mMaxRequestAmount = (Int32)(Math.Floor(CurrentUser.Cash1 / GetSystemSettingDecimal("PointsRate")) * GetSystemSettingDecimal("PointsRate"));
                    if(model.RequestAmount > mMaxRequestAmount || model.RequestAmount < mMinRequestAmount)
                    {
                        ModelState.AddModelError("", "购买数量错误");
                        return View(CalculatePointBuyModel());
                    }
                    CurrentUser.CashTransaction.Add(new CashTransaction
                    {
                        DateTime = DateTime.Now,
                        Status = 现金状态.已审核.ToString(),
                        Type = 现金交易类型.购买兑换券.ToString(),
                        Amount = -model.RequestAmount,
                        Fee = 0,
                    });
                    CurrentUser.PointTransaction.Add(new PointTransaction
                    {
                        DateTime = DateTime.Now,
                        Amount = model.RequestAmount,
                        Type = 兑换券记录类型.现金买入.ToString(),
                        Status = 兑换券状态.可用.ToString(),
                        Comment = "",
                    });
                    CurrentUser.Cash1 -= model.RequestAmount;
                    CurrentUser.Point1 += model.RequestAmount;
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            ModelState.AddModelError("", validationError.ToString());
                        }
                    }
                }
                ViewBag.ActionMessage = "购买成功！";
                TempData["ActionMessage"] = ViewBag.ActionMessage;
                return RedirectToAction("Success", "Message");
            }
            return View(CalculatePointBuyModel());
        }


        private PointBuyViewModel CalculatePointBuyModel()
        {
            return new PointBuyViewModel
            {
                AvailableCash = CurrentUser.Cash1,
                MinRequestAmount = (int)GetSystemSettingDecimal("PointsRate"),
                MaxRequestAmount = (Int32)(Math.Floor(CurrentUser.Cash1 / GetSystemSettingDecimal("PointsRate")) * GetSystemSettingDecimal("PointsRate"))
            };
        }

	}
}

MemberCenter/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberCenter.Models;

namespace MemberCenter.Controllers
{
    public class StoreController : BaseController
    {
        
        //
        // GET: /Store/ChongXiaoHistory
        public ActionResult ChongXiaoHistory()
        {
            IEnumerable<ConsumptionViewModel> model = from row in CurrentUser.ChongXiaoTransaction
                                                    orderby row.DateTime descending
                                                    select new ConsumptionViewModel
                                                    {
                                                        DateTime = row.DateTime,
                                                        Amount = row.Amount,
                                                        Comment = row.Comment,
                                                        Type = row.Type,
                                                    };
            SetMyAccountViewModel();
            return View(model);
        }


	}
}

MemberCenter/Views/Shared/NewSkin/_CaptchaPartial.cshtml
@model CaptchaMvc.Models.DefaultBuildInfoModel
<div>
    <div style="float:left;">
        @if (Model.IsRequired)
        {
            @Html.TextBox(Model.InputElementId, null, new Dictionary<string, object>
                                                  {
                                                      {"data-val", "true"},
                                                      {"data-val-required", Model.RequiredMessage}
                                                  })
        }
        else
        {
            @Html.TextBox(Model.InputElementId, null, new { @class = "form-control left", placeholder = "请输入验证码", maxlength = "4", @style="width:140px;" })
        }
    </div>

    <div style="float:left; width:110px;">
        <img id="@Model.ImageElementId" src="@Model.ImageUrl" style="width:70px; height:34px; float:left; margin-left:10px;" />
        @Html.Hidden(Model.TokenElementId, Model.TokenValue)
        <br />
        @{
            string id = Guid.NewGuid().ToString("N");
            string functionName = string.Format("______{0}________()", Guid.NewGuid().ToString("N"));
            <script type="text/javascript">

                $(function () {
                    $('#@id').show();
                });


                function @functionName {
                        $('#@id').hide();
                    $.post("@Model.RefreshUrl", { @Model.TokenParameterName: $('#@Model.TokenElementId').val() },
                        function () {
                            $('#@id').show();
                        });
                    return false;
                }
            </script>
            <a href="#@Model.InputElementId" id="@id" onclick="@functionName" style="display: none; float:right;">刷新</a>
        }
    </div>
    <br class="clear" />
</div>

MemberCenter/Views/Shared/NewSkin/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-cn">
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta charset="UTF-8">

    <title>联合通用积分会员系统 - @ViewBag.Title</title>

    <!-- CSS -->
    @Styles.Render("~/Content/new-skin/css/bootstrap.min.css")
    @Styles.Render("~/Content/new-skin/css/animate.min.css")
    @Styles.Render("~/Content/new-skin/css/font-awesome.min.css")
    @Styles.Render("~/Content/new-skin/css/form.css")
    @Styles.Render("~/Content/new-skin/css/calendar.css")
    @Styles.Render("~/Content/new-skin/css/style.css")
    @Styles.Render("~/Content/new-skin/css/icons.css")
    @Styles.Render("~/Content/new-skin/css/generics.css")
    @Styles.Render("~/Content/new-skin/custom.css")
    <!-- DataTables CSS -->
    @Styles.Render("~/Content/new-skin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")

    <link rel="shortcut icon" href="~/Content/new-skin/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/new-skin/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/new-skin/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/new-skin/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/new-skin/images/ico/apple-touch-icon-57-precomposed.png">

    <!-- Javascript Libraries -->
    <!-- jQuery -->
    @Scripts.Render("~/Content/new-skin/bower_components/jquery/dist/jquery.min.js")
    @Scripts.Render("~/Content/new-skin/js/jquery-ui.min.js") <!-- jQuery UI -->
    @Scripts.Render("~/Content/new-skin/js/jquery.easing.1.3.js") <!-- jQuery Easing - Requirred for Lightbox + Pie Charts-->
    <!-- Bootstrap -->
    @Scripts.Render("~/Content/new-skin/js/bootstrap.min.js")

    <!-- Charts -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.js") <!-- Flot Main -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.time.js") <!-- Flot sub -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.animator.min.js") <!-- Flot sub -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.resize.min.js") <!-- Flot sub - for repaint when resizing the screen -->
    
    @Scripts.Render("~/Content/new-skin/bower_components/jquery.cookie.js")

    <!-- DataTables JavaScript -->
    @Scripts.Render("~/Content/new-skin/bower_components/datatables/media/js/jquery.dataTables.js")
    @Scripts.Render("~/Content/new-skin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")

    @Scripts.Render("~/Content/new-skin/js/sparkline.min.js") <!-- Sparkline - Tiny charts -->
    @Scripts.Render("~/Content/new-skin/js/easypiechart.js") <!-- EasyPieChart - Animated Pie Charts -->
    @Scripts.Render("~/Content/new-skin/js/charts.js") <!-- All the above chart related functions -->
    <!-- All JS functions -->
    @Scripts.Render("~/Content/new-skin/js/functions.js")
</head>
<body id="skin-blur-ocean">

    <header id="header" class="media">
        <a href="" id="menu-toggle"></a>
        @Html.ActionLink("联合通用积分会员系统", "Index", "Home", null, new { @class = "logo pull-left" })

        <!--Top Toolkit-->
        <div class="media-body">
            <div class="media" id="top-menu">

                <div class="pull-left tm-icon">
                    <a data-drawer="notifications" class="drawer-toggle" href="#">
                        <i class="sa-top-updates"></i>
                        <i class="n-count animated hide">9</i>
                        <span>新闻中心</span>
                    </a>
                </div>

                <div id="time" class="pull-right">
                    当前时间： <span id="hours"></span>:<span id="min"></span>:<span id="sec"></span>
                </div>

                <div class="media-body">
                    <input type="text" class="main-search">
                </div>
            </div>
        </div>
    </header>

    <div class="clearfix"></div>

    <section id="main" class="p-relative" role="main">

        <!-- Sidebar -->
        <aside id="sidebar">

            <!-- Sidbar Widgets -->
            @Html.Partial("NewSkin/_MyAccountPartial")

            @Html.Partial("NewSkin/_Navigation")

        </aside>

        <!-- Content -->
        <section id="content" class="container">

            @Html.Partial("NewSkin/_NewsListPartial")

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4 class="page-title" style="margin-bottom:20px;">@ViewBag.Title</h4>

                            @RenderBody()
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

        </section>

    </section>


    <div id="form-loading"><span class="loading-box"><img src="~/Content/new-skin/images/loading.gif" class="loading" /></span></div>
    <script language="javascript">

        $(function () {
            $('#form-loading').hide();
            $('form').submit(function () {
                $('#form-loading').show();
            });
            
        });
    </script>

</body>
</html>

MemberCenter/Views/Shared/NewSkin/_LayoutHome.cshtml
@using MemberCenter.Helper
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>联合通用积分会员系统 - @ViewBag.Title</title>
    @Styles.Render("~/Content/new-skin/css/bootstrap.min.css")
    @Styles.Render("~/Content/new-skin/css/font-awesome.min.css")
    @Styles.Render("~/Content/new-skin/css/prettyPhoto.css")
    @Styles.Render("~/Content/new-skin/css/main.css")
    @Styles.Render("~/Content/new-skin/custom.css")
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="~/Content/new-skin/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/new-skin/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/new-skin/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/new-skin/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/new-skin/images/ico/apple-touch-icon-57-precomposed.png">

    @Scripts.Render("~/Content/new-skin/js/jquery.js")
    @Scripts.Render("~/Content/new-skin/js/bootstrap.min.js")
    @Scripts.Render("~/Content/new-skin/js/jquery.isotope.min.js")
    @Scripts.Render("~/Content/new-skin/js/jquery.prettyPhoto.js")
    @Scripts.Render("~/Content/new-skin/js/main.js")

    <!-- Charts -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.js") <!-- Flot Main -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.time.js") <!-- Flot sub -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.animator.min.js") <!-- Flot sub -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.resize.min.js") <!-- Flot sub - for repaint when resizing the screen -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.orderBar.js") <!-- Flot Bar chart -->
    @Scripts.Render("~/Content/new-skin/js/charts/jquery.flot.pie.min.js") <!-- Flot Pie chart -->

</head><!--/head-->
<body data-spy="scroll" data-target="#navbar" data-offset="0">
    <header id="header" role="banner">
        <div class="container">
            <div id="navbar" class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href=""></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#main-slider"><i class="icon-home"></i></a></li>
                        <li><a href="#services">数字资产</a></li>
                        <li><a href="#" onclick="window.open('@SiteConfigurationHelper.SiteRootPath/Home/Dashboard', '_blank');">交易中心</a></li>
                        <li><a href="#portfolio">实时行情</a></li>
                        <li><a href="#pricing" class="hide">交易数据</a></li>
                        <li><a href="#about-us" class="hide">关于我们</a></li>
                        <li><a href="#contact">客服中心</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header><!--/#header-->
    
    
    @RenderBody()

    
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 SafenLife.com 山东宏仁国际贸易有限公司. All Rights Reserved.
                </div>
                <div class="col-sm-6">

                </div>
            </div>
        </div>
    </footer><!--/#footer-->
    

</body>
</html>

MemberCenter/Views/Shared/NewSkin/_LayoutLogin.cshtml
@using MemberCenter.Helper
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Feng">

    <title>联合通用积分会员系统 - @ViewBag.Title</title>

    <!-- Bootstrap Core CSS -->
    @Styles.Render("~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css")

    <!-- MetisMenu CSS -->
    @Styles.Render("~/Content/bower_components/metisMenu/dist/metisMenu.min.css")

    <!-- Custom CSS -->
    @Styles.Render("~/Content/dist/css/sb-admin-2.css")
    @Styles.Render("~/Content/css/custom.css")

    <!-- Custom Fonts -->
    @Styles.Render("~/Content/bower_components/font-awesome/css/font-awesome.min.css")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="~/Content/new-skin/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/new-skin/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/new-skin/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/new-skin/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/new-skin/images/ico/apple-touch-icon-57-precomposed.png">


    @Scripts.Render("~/Content/bower_components/jquery/dist/jquery.min.js")
    @Scripts.Render("~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js")
    @Scripts.Render("~/Content/bower_components/metisMenu/dist/metisMenu.min.js")
    @Scripts.Render("~/Content/dist/js/sb-admin-2.js")
    @RenderSection("scripts", required: false)
</head>


<body class="login">

    <div id="wrapper">
        @RenderBody()
    </div>
    <!-- /#wrapper -->
</body>

</html>

MemberCenter/Views/Shared/NewSkin/_Navigation.cshtml
@using MemberCenter.Helper

<!-- Side Menu -->
<ul class="list-unstyled side-menu">
    <li>
        <a class="sa-side-home" href="@SiteConfigurationHelper.SiteRootPath/Account/MyAssets"><span class="menu-item">首页</span></a>
    </li>
    <li class="dropdown">
        <a class="sa-side-page" href="#">
            <span class="menu-item">个人中心</span>
        </a>
        <ul class="list-unstyled menu-item">
            <li>@Html.ActionLink("个人信息", "MyAccount", "Account")</li>
            <li>@Html.ActionLink("我的会员", "MyMembers", "Account")</li>
        </ul>
    </li>
    <li class="dropdown">
        <a class="sa-side-table" href="#">
            <span class="menu-item">财务中心</span>
        </a>
        <ul class="list-unstyled menu-item">
            <li>@Html.ActionLink("资金充值", "CashTopup", "Transaction")</li>
            <li>@Html.ActionLink("资金提现", "CashWithdraw", "Transaction")</li>
            <li>@Html.ActionLink("资金转账", "Transfer", "Transaction")</li>
            <li>@Html.ActionLink("资金记录", "History", "Transaction")</li>
        </ul>
    </li>
    <li class="dropdown">
        <a class="sa-side-widget" href="#">
            <span class="menu-item">报单中心</span>
        </a>
        <ul class="list-unstyled menu-item">
            <li>@Html.ActionLink("实价报单", "Buy", "BaoDan")</li>
            <li>@Html.ActionLink("积分解冻", "LockedCoins", "BaoDan")</li>
        </ul>
    </li>
    <li class="dropdown">
        <a class="sa-side-chart" href="#">
            <span class="menu-item">积分中心</span>
        </a>
        <ul class="list-unstyled menu-item">
            <li>@Html.ActionLink("积分卖出", "Sell", "BaoDan")</li>
            <li>@Html.ActionLink("积分转账", "Transfer", "BaoDan")</li>
            <li>@Html.ActionLink("积分消费", "Consume", "BaoDan")</li>
            <li>@Html.ActionLink("积分记录", "History", "BaoDan")</li>
        </ul>
    </li>
    <li class="dropdown">
        <a class="sa-side-chart" href="#">
            <span class="menu-item">会员商城</span>
        </a>
        <ul class="list-unstyled menu-item">
            <li>@Html.ActionLink("购买兑换券", "Buy", "Points")</li>
            <li>@Html.ActionLink("兑换券转账", "Transfer", "Points")</li>
            <li>@Html.ActionLink("兑换券记录", "History", "Points")</li>
            <li>@Html.ActionLink("重消记录", "ChongXiaoHistory", "Store")</li>
        </ul>
    </li>
    <li class="dropdown">
        <a class="sa-side-calendar" href="#">
            <span class="menu-item">安全中心</span>
        </a>
        <ul class="list-unstyled menu-item">
            <li>@Html.ActionLink("登录日志", "IPLog", "Account")</li>
            <li>@Html.ActionLink("安全设置", "SecureSetting", "Account")</li>
        </ul>
    </li>
</ul>

MemberCenter/Views/Shared/NewSkin/_NewsListPartial.cshtml

<!-- News Center -->
<div id="notifications" class="tile drawer animated">
    <div class="listview narrow">
        <div class="media">
            <a href="#">新闻中心</a>
            <span class="drawer-close">&times;</span>
        </div>
        <div class="overflow" style="height: 254px">

            <div class="media">
                <div class="pull-left">
                    <img width="40" src="~/Content/new-skin/img/profile-pics/2.jpg" alt="">
                </div>
                <div class="media-body">
                    <small class="text-muted">新闻标题 16/12/2013</small><br>
                    <a class="t-overflow" href="">新版会员中心隆重上线</a>
                </div>
            </div>
        </div>
        <div class="media text-center whiter l-100">
            <a href="#"><small>显示全部</small></a>
        </div>
    </div>
</div>