Backend/Models/CashTransaction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransaction
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public decimal Fee { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> BaoDanTransactionId { get; set; }
        public string Bank { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string Comment { get; set; }
        public string FileUrl { get; set; }
        public string RemitBank { get; set; }
        public string RemitUserName { get; set; }
        public string RemitNumber { get; set; }
    
        public virtual BaoDanTransaction BaoDanTransaction { get; set; }
        public virtual Member Member { get; set; }
    }
}

Backend/Models/CashViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Backend.Models
{

    public class CashTransactionViewModel
    {
        [Display(Name = "交易ID")]
        public int ID { get; set; }

        [Display(Name = "交易时间")]
        public DateTime DateTime { get; set; }

        [Display(Name = "状态")]
        public String Status { get; set; }

        [Display(Name = "资金类型")]
        public String Type { get; set; }

        [Display(Name = "交易金额")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal Amount { get; set; }

        [Display(Name = "手续费")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal Fee { get; set; }

        public int MemberId { get; set; }

        public string MemberEmail { get; set; }

        public string Bank { get; set; }

        public string RemitNumber { get; set; }

        public string RemitAccount { get; set; }

        public string FileUrl { get; set; }

        public string Comment { get; set; }
    }

    public class CashWithdrawHistoryViewModel
    {
        [Display(Name = "提现时间")]
        public DateTime WithdrawTime { get; set; }

        [Display(Name = "提现金额")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal Amount { get; set; }

        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal AmountDisp { get { return Math.Abs(Amount); } }

        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal RealAmount { get { return Math.Abs(Amount) - Fee; } }

        [Display(Name = "手续费")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal Fee { get; set; }

        [Display(Name = "银行")]
        public String Bank { get; set; }

        [Display(Name = "账户")]
        public String BankAccount { get; set; }

        [Display(Name = "状态")]
        public String Status { get; set; }

        public int Id { get; set; }

        public int MemberId { get; set; }

        public string MemberEmail { get; set; }

    }

}

Backend/Controllers/CashController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Backend.Helper;
using Backend.Models;
using VapLib;

namespace Backend.Controllers
{
   
    public class CashController : Controller
    {
        private vapEntities1 db = new vapEntities1();
        private static object dbLock = new object();

        /// <summary>
        /// 所有cash 操作记录
        /// </summary>
        /// <returns></returns>
        [MyAuthorize(Roles = "Admin,Finance")]
        public ActionResult CashTrans(string type,string status,string memberAccount,string startDate,string endDate)
        {
            var start = DateTime.Now;
            var end = DateTime.Now;
            if (!DateTime.TryParse(startDate, out start) &&!string.IsNullOrEmpty(startDate))
            {
                ModelState.AddModelError("","起始日期格式输入不正确");
                return View();
            }
            if (!DateTime.TryParse(endDate, out end) && !string.IsNullOrEmpty(endDate))
            {
                ModelState.AddModelError("", "截止日期格式输入不正确");
                return View();
            }
            var records = db.CashTransactions.Include(c=>c.Member);
            if (!string.IsNullOrEmpty(type))
            {
                records = records.Where(c => c.Type == type);
            }
            if (!string.IsNullOrEmpty(status))
            {
                records = records.Where(c => c.Status == status);
            }
            if (!string.IsNullOrEmpty(memberAccount))
            {
                records = records.Where(c => c.Member.Email.Contains(memberAccount));
            }
            if (!string.IsNullOrEmpty(startDate))
            {
                records = records.Where(c => c.DateTime>=start);
            }
            if (!string.IsNullOrEmpty(endDate))
            {
                end = end.AddDays(1);
                records = records.Where(c => c.DateTime <end);
            }
            ViewBag.memberAccount = memberAccount;
            ViewBag.status = status;
            ViewBag.type = type;
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;

            IEnumerable<CashTransactionViewModel> modle = from row in records
                                                          select new CashTransactionViewModel
                                                          {
                                                              Type = row.Type,
                                                              Status = row.Status,
                                                              DateTime = row.DateTime,
                                                              Fee = row.Fee,
                                                              Amount = row.Amount,
                                                              ID = row.Id,
                                                              FileUrl = row.FileUrl,
                                                              Bank = row.Bank,
                                                              RemitNumber = row.RemitNumber,
                                                              RemitAccount = row.RemitUserName,
                                                              MemberEmail = row.Member.Email,
                                                              MemberId = row.Member.Id,
                                                              Comment = row.Comment
                                                          };
            return View(modle);
        }
        /// <summary>
        /// 待审批现金充值记录
        /// </summary>
        /// <returns></returns>
        [MyAuthorize(Roles = "Admin")]
        public ActionResult PendingTopups(string startDate, string endDate)
        {
            if (TempData.ContainsKey("ModelState"))
            {
                ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);
            }
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            var status =现金状态.待审核.ToString();
            var type = 现金交易类型.充值.ToString();
            var cashtransactions = db.CashTransactions.Where(c => c.Status == status
                                                                  && c.Type == type)
                                                                  ;
            if (!string.IsNullOrEmpty(startDate))
            {
                DateTime start;
                DateTime.TryParse(startDate, out start);
                cashtransactions = cashtransactions.Where(c => c.DateTime >= start);
            }
            if (!string.IsNullOrEmpty(endDate))
            {
                DateTime end;
                DateTime.TryParse(endDate, out end);
                end = end.AddDays(1);
                cashtransactions = cashtransactions.Where(c => c.DateTime < end);
            }
            return View(cashtransactions.OrderBy(c => c.DateTime).ToList());
        }
        /// <summary>
        /// 会员冻结积分记录
        /// </summary>
        /// <returns></returns>
        [MyAuthorize(Roles = "Admin")]
        public ActionResult MemberLocks(int memberId)
        {
            if (TempData.ContainsKey("ModelState"))
            {
                ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);
            }
            //var status = 现金状态.冻结.ToString();
            //var type = 现金交易类型.充值.ToString();
            var lockedCv = db.LockedCoins.Where(c => c.MemberId == memberId
                                                && c.LockedAmount >0).ToList()
                                                .Select(c=>new LockedCoinViewModel(c));

            return View(lockedCv);
        }
        [MyAuthorize(Roles = "Admin")]
        public ActionResult UnlockCashTrans(int id)
        {

            var record = db.LockedCoins.Find(id);
            var member = db.Members.Find(record.MemberId);
            if(record.LockedAmount>0)
            {
                var amount = record.LockedAmount;
                record.AvailabeAmount = record.TotalAmount;
                record.LockedAmount = 0;
                
               
                member.Coin1 += amount;
                member.Coin2 -= amount;

                db.Entry(member).State = EntityState.Modified;
                db.Entry(record).State = EntityState.Modified;
                db.SaveChanges();
                ModelState.AddModelError("", "解冻操作执行成功。");
            }
            else
            {
                ModelState.AddModelError("", "没有符合的记录。");
            }
            

            TempData["ModelState"] = ModelState;
            return RedirectToAction("MemberLocks",new{memberId=member.Id});
           
        }
        /// <summary>
        /// 会员现金充值记录
        /// </summary>
        /// <returns></returns>
        [MyAuthorize(Roles = "Admin")]
        
        public ActionResult MemberTopups(int memberId)
        {
            
            //var status = 现金状态.待审核.ToString();
            var type = 现金交易类型.充值.ToString();
            var cashtransactions = db.CashTransactions.Where(c => c.MemberId == memberId
                                                                  && c.Type == type)
                                                                  .OrderBy(c => c.DateTime);

            IEnumerable<CashTransactionViewModel> model = from row in cashtransactions
                                                          select new CashTransactionViewModel
                                                          {
                                                              Type = row.Type,
                                                              Status = row.Status,
                                                              DateTime = row.DateTime,
                                                              Fee = row.Fee,
                                                              Amount = row.Amount,
                                                              ID = row.Id,
                                                              FileUrl = row.FileUrl,
                                                              Bank = row.Bank,
                                                              RemitNumber = row.RemitNumber,
                                                              RemitAccount = row.RemitUserName,
                                                              Comment = row.Comment
                                                          };
            return View(model);
        }
        /// <summary>
        /// 会员提现记录
        /// </summary>
        /// <returns></returns>
        [MyAuthorize(Roles = "Admin")]
        public ActionResult MemberWithdraws(int memberId)
        {

            //var status = 现金状态.待审核.ToString();
            var type = 现金交易类型.提现.ToString();
            var cashtransactions = db.CashTransactions.Where(c => c.MemberId == memberId
                                                                  && c.Type == type)
                                                                  .OrderBy(c => c.DateTime);
            return View(cashtransactions.ToList());
        }

        [MyAuthorize(Roles = "Admin,Finance")]
        public ActionResult PendingWithdraws(string startDate,string endDate)
        {
            if (TempData.ContainsKey("ModelState"))
            {
                ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);
            }
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            var status = 现金状态.待审核.ToString();
            var type = 现金交易类型.提现.ToString();
            
            var cashtransactions = db.CashTransactions.Where(c => c.Status == status
                                                                  && c.Type == type);

Backend/Views/Cash/ApproveCashTrans.cshtml
@using Backend.Helper
@model Backend.Models.CashTransaction

@{
    ViewBag.Title = "现金业务审核";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="place">
    <span>位置：</span>
    <ul class="placeul">
        <li><a href="@Url.Action("Index","Home")">首页</a></li>
        <li><a href="#">现金业务审核</a></li>
    </ul>
</div>
<div class="formbody">
    <div class="formtitle"><span>现金业务信息</span></div>
    <div class="toolsli">
        <ul class="toollist">
            <li><h2>会员账号： @Html.DisplayFor(model => model.Member.Email) </h2></li>
            <li><h2>类型： @Html.DisplayFor(model => model.Type) </h2></li>
            <li><h2>银行： @Html.DisplayFor(model => model.Bank)</h2></li>
            <li><h2>银行账号： @Html.DisplayFor(model => model.BankAccount)</h2></li>
            <li><h2>账号名称： @Html.DisplayFor(model => model.BankName)</h2></li>
            <li><h2>转账金额： @Html.DisplayFor(model => model.Amount)</h2></li>
            <li><h2>转账时间： @Html.DisplayFor(model => model.DateTime)</h2></li>


            
        </ul>

    </div>
    @if (Model.Type == VapLib.现金交易类型.充值.ToString())
    {
        <div class="formtitle"><span>充值凭证信息</span></div>
        <div class="toolsli">
            <ul class="toollist">

                <li><a href="@SiteConfigurationHelper.UploadFolderPath@Model.FileUrl" target="_blank" style="width: 50%; display: inline;"><img src="@SiteConfigurationHelper.UploadFolderPath@Model.FileUrl" style="width: 50%;" /></a><h2>凭证照片</h2></li>

            </ul>

        </div>
    }
</div>
<div class="toolsli">
    <ul class="toollist">

       @using (Html.BeginForm())
       {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.Id)

        <li><label>&nbsp;</label><input name="" type="submit" class="btn" value="批准" /></li>


       }

    </ul>

</div>
<script>
    $(document).ready(function () {

        $('#cashParent').slideDown();
    });
</script>

Backend/Views/Cash/CashTrans.cshtml
@model IEnumerable<Backend.Models.CashTransactionViewModel>
@using VapLib
@using Backend.Helper


@{
    ViewBag.Title = "资金操作记录查询";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var total = 0m;
}

<div class="place">
    <span>位置：</span>
    <ul class="placeul">
        <li><a href="@Url.Action("Index","Home")">首页</a></li>
        <li><a href="#">资金操作记录查询</a></li>
    </ul>
</div>
<div class="formbody">
    @using (Html.BeginForm("CashTrans", "Cash", FormMethod.Get))
    {
        @Html.ValidationSummary()
        <ul class="seachform1">
            <li>
                <label>会员账号</label>
                @Html.TextBox("memberAccount", "", new { @class = "scinput1" })
            </li>
            <li>
                <label>状态</label>
                @{
                    var options = new List<SelectListItem>();
                    options.Insert(0, new SelectListItem
                    {
                        Text = "全部",
                        Value = ""
                    });
                    options.Insert(1, new SelectListItem
                    {
                        Text = "待审核",
                        Value = "待审核"
                    });
                    options.Insert(2, new SelectListItem
                    {
                        Text = "已审核",
                        Value = "已审核"
                    });
                    options.Insert(3, new SelectListItem
                    {
                        Text = "冻结",
                        Value = "冻结"
                    });


                }
                @Html.DropDownList("status", options, new { @class = "scinput1" })

            </li>
            <li>
                <label>类型</label>
                @{
                    var options1 = new List<SelectListItem>();
                    options1.Insert(0, new SelectListItem
                    {
                        Text = "全部",
                        Value = ""
                    });
                    options1.Insert(1, new SelectListItem
                    {
                        Text = "充值",
                        Value = "充值"
                    });
                    options1.Insert(2, new SelectListItem
                    {
                        Text = "提现",
                        Value = "提现"
                    });
                    options1.Insert(3, new SelectListItem
                    {
                        Text = "下线返利",
                        Value = "下线返利"
                    });
                    options1.Insert(4, new SelectListItem
                    {
                        Text = "购买积分",
                        Value = "购买积分"
                    });
                    options1.Insert(5, new SelectListItem
                    {
                        Text = "积分出售",
                        Value = "积分出售"
                    });
                    options1.Insert(6, new SelectListItem
                    {
                        Text = "会员转入",
                        Value = "会员转入"
                    });
                    options1.Insert(7, new SelectListItem
                    {
                        Text = "会员转出",
                        Value = "会员转出"
                    });
                    
                }
                @Html.DropDownList("type", options1, new { @class = "scinput1" })

            </li>

            
        </ul>
        <ul class="seachform1">
            <li>
                <label>起始时间</label>
                @Html.TextBox("startDate", "", new { @class = "scinput1" ,@Type="Date"})
            </li>
            <li>
                <label>截止时间</label>
                @Html.TextBox("endDate", "", new { @class = "scinput1", @Type = "Date" })
            </li>
            <li class="sarchbtn">
                <input name="" type="submit" class="scbtn" value="查询" />
                @*<input name="" type="button" class="scbtn2" value="导出" />*@
            </li>
        </ul>
        



        @*<a class="btn-primary" href="@Url.Action("CreateUser","Admin")">新建账号</a>*@

    }
    <div class="formtitle"><span>记录列表</span></div>
    <table id="dataTable-Cash">
        <thead>
            <tr>
                <th>
                    会员账号(UID)
                </th>
                <th>
                    金额
                </th>
                <th>
                    类型
                </th>
                <th>
                    状态
                </th>
                <th style="width:300px;">
                    备注
                </th>
                <th>
                    时间
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                total += item.Amount;
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MemberEmail) (@Html.DisplayFor(modelItem => item.MemberId))
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td style="">
                        @if (item.Type == 现金交易类型.充值.ToString())
                        {
                            <a href="@SiteConfigurationHelper.UploadFolderPath@item.FileUrl" style="text-decoration: underline;" target="_blank">@Html.DisplayFor(modelItem => item.Type)</a>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Type)
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Comment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateTime)
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <span class="text-danger "><b>金额汇总：￥@total</b></span>
</div>
<script>
    $(document).ready(function () {
        $('#dataTable-Cash').DataTable({
            "searching": false,
        });
        $('#cashParent').slideDown();
    });
</script>

Backend/Views/Cash/PendingTopups.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Backend.Models.CashTransaction>

@{
    ViewBag.Title = "待审批现金充值";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var total = 0m;
}

<div class="place">
    <span>位置：</span>
    <ul class="placeul">
        <li><a href="@Url.Action("Index","Home")">首页</a></li>
        <li><a href="#">待审批现金充值</a></li>
    </ul>
</div>
<div class="formbody">
    @Html.ValidationSummary()
    @using (Html.BeginForm("PendingTopups", "Cash", FormMethod.Get))
    {

        <ul class="seachform1">
            <li>
                <label>起始时间</label>
                @Html.TextBox("startDate", "", new { @class = "scinput1", @Type = "Date" })
            </li>
            <li>
                <label>截止时间</label>
                @Html.TextBox("endDate", "", new { @class = "scinput1", @Type = "Date" })
            </li>
            <li class="sarchbtn">
                <input name="" type="submit" class="scbtn" value="查询" />
                @*<input name="" type="button" class="scbtn2" value="导出" />*@
            </li>
        </ul>
    }
    @*<ul class="seachform1">

        <li><label>会员账号</label><input name="" type="text" class="scinput1" /></li>
        <li>
            <label>会员UID</label>
            <input name="" type="text" class="scinput1" />
        </li>

        <li>
            <label>状态</label>
            <select class="scinput1">
                <option>全部</option>
                <option>待审核</option>
                <option>可用</option>
                <option>冻结</option>
            </select>
        </li>


    </ul>



    <ul class="seachform1">
        <li class="sarchbtn">
            <label>&nbsp;</label>
            <input name="" type="button" class="scbtn" onclick="" value="查询" />
        </li>
    </ul>

*@

    
    <div class="formtitle"><span>待审批现金充值列表</span></div>
    <div style="padding: 10px 20px ;float: right;">
        <a href="@Url.Action("CashTrans","Cash",new{status="已审核",type="充值"} )" Style="padding: 3px" class="scbtn">已审核的充值记录</a>
    </div>
    <table @*class="tablelist"*@ id="dataTable-Topups">
        <thead>
            <tr>
                <th>
                    会员账号
                </th>
                <th>
                    会员UID
                </th>
                <th>
                    金额
                </th>
                <th>
                    类型
                </th>
                <th>
                    状态
                </th>
                <th>
                    银行
                </th>
                <th>
                    汇款单号
                </th>
                <th>
                    申请时间
                </th>

                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                total += item.Amount;
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Member.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MemberId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Bank)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RemitNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateTime)
                    </td>

                    <td>
                        @Html.ActionLink("批准", "ApproveCashTrans", new { id = item.Id }, new { @class = "tablelink" })
                        |
                        @Html.ActionLink("删除", "DeleteCashTrans", new { id = item.Id,type="T" }, new { @class = "tablelink", onclick = "javascript:return confirm('确认删除？')" })


                    </td>
                </tr>
            }
        </tbody>
    </table>
    <span class="text-danger "><b>金额汇总：￥@total</b></span>
</div>
<script>
    $(document).ready(function () {
        $('#dataTable-Topups').DataTable({
            "searching": true,
        });
        $('#cashParent').slideDown();
    });
</script>

Backend/Views/Cash/PendingWithdraws.cshtml
@model IEnumerable<Backend.Models.CashWithdrawHistoryViewModel>

@{
    ViewBag.Title = "待审批现金提现";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var total = 0m;
}

<div class="place">
    <span>位置：</span>
    <ul class="placeul">
        <li><a href="@Url.Action("Index","Home")">首页</a></li>
        <li><a href="#">待审批现金提现</a></li>
    </ul>
</div>
<div class="formbody">
    @Html.ValidationSummary()
    @using (Html.BeginForm("PendingWithdraws", "Cash", FormMethod.Get))
    {
        
        <ul class="seachform1">
            <li>
                <label>起始时间</label>
                @Html.TextBox("startDate", "", new { @class = "scinput1", @Type = "Date" })
            </li>
            <li>
                <label>截止时间</label>
                @Html.TextBox("endDate", "", new { @class = "scinput1", @Type = "Date" })
            </li>
            <li class="sarchbtn">
                <input name="" type="submit" class="scbtn" value="查询" />
                @*<input name="" type="button" class="scbtn2" value="导出" />*@
            </li>
        </ul>
    }
    @*<ul class="seachform1">

        <li><label>会员账号</label><input name="" type="text" class="scinput1" /></li>
        <li>
            <label>会员UID</label>
            <input name="" type="text" class="scinput1" />
        </li>

        <li>
            <label>状态</label>
            <select class="scinput1">
                <option>全部</option>
                <option>待审核</option>
                <option>可用</option>
                <option>冻结</option>
            </select>
        </li>


    </ul>



    <ul class="seachform1">
        <li class="sarchbtn">
            <label>&nbsp;</label>
            <input name="" type="button" class="scbtn" onclick="" value="查询" />
        </li>
    </ul>

*@


    <div class="formtitle"><span>待审批现金提现列表</span></div>
    <div style="padding: 10px 20px ;float: right;">
        <a href="@Url.Action("CashTrans", "Cash", new { status = "已审核", type = "提现" })" style="padding: 3px" class="scbtn">已审核的提现记录</a>
    </div>
    <table @*class="tablelist"*@ id="dataTable-Withdraws">
        <thead>
            <tr>
                <th>
                    会员账号
                </th>
                <th>
                    会员UID
                </th>
                <th>
                    申请提现
                </th>
                <th>
                    手续费
                </th>
                <th>
                    实提金额
                </th>
                <th>
                    状态
                </th>
                <th>
                    银行
                </th>
                <th>
                    申请时间
                </th>

                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                total += item.Amount;
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MemberEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MemberId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RealAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Bank)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WithdrawTime)
                    </td>

                    <td>
                        @Html.ActionLink("批准", "ApproveCashTrans", new { id = item.Id }, new { @class = "tablelink" })
                        |
                        @Html.ActionLink("删除", "DeleteCashTrans", new { id = item.Id ,type="W"}, new { @class = "tablelink", onclick = "javascript:return confirm('确认删除？')" })


                    </td>
                </tr>
            }
        </tbody>
    </table>
    <span class="text-danger "><b>申请提现金额汇总：￥@total</b></span>
</div>
<script>
    $(document).ready(function () {
        $('#dataTable-Withdraws').DataTable({
            "searching": false,
        });
        $('#cashParent').slideDown();
    });
</script>